# Generated by Django 4.2.5 on 2023-10-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('pincode', models.CharField(max_length=100, verbose_name='Pincode')),
                ('phone_no', models.IntegerField(verbose_name='Phone No')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('team', models.CharField(max_length=100, verbose_name='Team')),
            ],
        ),
    ]
