# Generated by Django 4.2.5 on 2023-10-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_created_at_employee_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.IntegerField(verbose_name='Phone No'),
        ),
    ]
