# Generated by Django 4.2.5 on 2023-10-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_dob_alter_employee_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone No'),
        ),
    ]
