# Generated by Django 4.2.5 on 2023-10-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_address_alter_employee_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
