# Generated by Django 4.2.5 on 2023-10-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, default=0, null=True),
        ),
    ]
