# Generated by Django 4.2.5 on 2023-10-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
