# Generated by Django 4.2.5 on 2023-10-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_employee_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='employees/files/images/'),
        ),
    ]
