# Generated by Django 4.2.5 on 2023-10-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_alter_employee_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_img',
            field=models.ImageField(default='default.png', null=True, upload_to='employees/profile_images/'),
        ),
    ]
