# Generated by Django 4.2.5 on 2023-10-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_alter_employee_access_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='employees/profile_images/'),
        ),
    ]
