# Generated by Django 4.2.5 on 2023-10-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='Employee_name_id',
            new_name='employee_name_id',
        ),
    ]
