# Generated by Django 4.2.5 on 2023-10-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_attendence_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='checked_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
